version: '3'

services:
  web:
    build: .
    container_name: aura-spa
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
